spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
logging:
  level:
    root: INFO
    com.ecom.user: DEBUG
  file:
    name: logs/${spring.application.name}.log