spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGO_URL}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    root: INFO
    com.ecom.user: DEBUG
  file:
    name: logs/${spring.application.name}.log

